[package]
name = "vrm-viewer"
publish = false
version = "0.0.0"
edition = "2021"
repository = "https://github.com/kayhhh/vrm-viewer"
license = "GPL-3.0-or-later"

[features]
default = ["native"]
native = ["bevy/x11"]
web = ["bevy/webgl2"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
bevy = { version = "0.12.1", default-features = false, features = ["animation", "bevy_asset", "bevy_scene", "bevy_winit", "bevy_core_pipeline", "bevy_pbr", "bevy_gltf", "bevy_render", "png"] }
bevy_blob_loader = "0.0.3"
bevy_vrm = "0.0.7"
bevy_web_file_drop = "0.0.1"
wasm-bindgen = "0.2.89"
