[package]
name = "vrm-viewer"
publish = false
version = "0.0.0"
edition = "2021"
repository = "https://github.com/kayhhh/vrm-viewer"
license = "GPL-3.0-or-later"

[profile.release]
lto = true

[profile.wasm-release]
inherits = "release"
opt-level = "z"
